### ISSUE TITLE
Mark Assignment 3 of Laura Z

### ISSUE THREAD

**Issue by lzgles** [lzgles/week_03#1]
@rharrington31

I'm not sure why, but my git push origin master was trying to push to your UD-PCS week 3 repository instead of mine, so I was getting a Permission Denied error. I fixed it by deleting my week_03 folder, re-cloning from your repository, copying my finished assignment to the new folder, and following the steps again as normal. I don't know how I messed it up in the first place but it worked as expected the second time.

**Comment by rharrington31** [comment]
1. Good. That could be one reason for using that parameter in `col_types`. Also consider how `read_csv` goes about guessing column types and what the impact of `NA` values might be on that.
2. Good.
3. Good! Very complete.
4. Great!
5. Good!
6. Nice job - consider some ways to make this easier for yourself though. For example, instead of using `|`, you might consider `%in%`. Further, you could consider how to avoid hardcoding the `make` values in the first place.
7. Nice job. Interesting question, good approach to answering it.
8. This sounds like a great course project. I'm excited to learn more about your work through this analysis. No worries if the dataset changes slightly - if it looks similar to what you sent, it should be great.
